# Generated by Django 4.0.6 on 2022-07-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('hiring_date', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
