# Generated by Django 4.0.6 on 2022-07-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('hiring_date', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='employee',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.boss'),
        ),
    ]
